checks:
  php:
    code_rating: true
    duplication: true
filter:
  excluded_paths:
    - tests/*
build:
  environment:
    php:
      version: '5.4'
  tests:
    override:
      - command: composer test
        coverage:
          file: tests/Report/coverage.xml
          format: php-clover
